# permissions for end users to edit ldapconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ldapconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: webhook-operator
    app.kubernetes.io/part-of: webhook-operator
    app.kubernetes.io/managed-by: kustomize
  name: ldapconfig-editor-role
rules:
- apiGroups:
  - ldap.tokenservice.com
  resources:
  - ldapconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ldap.tokenservice.com
  resources:
  - ldapconfigs/status
  verbs:
  - get
